steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/javaproject/amazingapp:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/javaproject/amazingapp:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'amazingapp'
    - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/javaproject/amazingapp:$COMMIT_SHA'
    - '--region=us-central1'
    - '--platform=managed'
    - '--port=8080'
    - '--allow-unauthenticated'

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/javaproject/amazingapp:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY